import {Form, useOutletContext } from "react-router";
import { Dropdown, InputField }  from "../../components/FormComponents";
import { ClientFormData } from "../../components/types";

// This should have stuff like the forwards and back arrows etc, save button, etc.
// If save button is pressed it needs to send an action to the relevant page so that it takes data and uploads it to the db.
// This will also have a complete button and whenever it's pressed it'll make sure the current page saves then it'll redirect you to the home page.
// Will need to make sure that before any re-render that the data is saved so they don't lose data because of authentication
function OnboardForm( ){
  // All state passed into this, when button is clicked it all goes to that for processing.
  const formStateHandler: { formState: any, updateFormState: Function} = useOutletContext();
  const updateFormState = formStateHandler.updateFormState;
  const formState = formStateHandler.formState;

  return(
    <>
      <p className="requiredField">Fields marked with * are required</p>
      <Form action="" method="post">
        <span>Client Name: </span>
        <input name="ClientName" defaultValue={formState["ClientName"]} onChange={(e) => {formState["ClientName"] = e.target.value; updateFormState(formState)}}></input>
        <Dropdown name="ClientType" label="Client Type:" options={["Individual", "Company"]}  updateState={updateFormState} formState={formState} required={true}/>
        {/* Office */}
        <Dropdown name="Office" label="Office:" options={["Norwich"]} updateState={updateFormState} formState={formState} required={true} />

        <Dropdown name="Department" label="Department:" options={["Business"]} updateState={updateFormState} formState={formState} required={true}/>

        <Dropdown name="Partner" label="Partner:" options={["Generated by db request"]} updateState={updateFormState} formState={formState} required={true}/>

        <InputField name="Manager" label="Manager:" updateState={updateFormState} formState={formState}/> 

        <InputField name="CaseWorker" label="Case Worker:" updateState={updateFormState} formState={formState}/>

      </Form>
    </>
  )
}

export default OnboardForm
