import { useOutletContext } from "react-router";
import { Dropdown, InputField }  from "../../components/FormComponents";
import { useEffect, useState } from "react";
import axios from "axios";

function Page1(){
  const formStateHandler: { formState: any, updateFormState: Function, setCanProceed: any} = useOutletContext();
  const updateFormState = formStateHandler.updateFormState;
  const formState = formStateHandler.formState;
  const setCanProceed = formStateHandler.setCanProceed;

  const [isValidCompany, setIsValidCompany] = useState(true);

  let defaultCompanyName = "";

  if (formState.FormState["CompanyNameCheck"]){
    defaultCompanyName = formState.FormState["CompanyNameCheck"];
  }
  const [companyName, setCompanyName] = useState(defaultCompanyName);

  const onClientTypeChanged = (event: any) => {
    const clientType = event.target.value;
    formState.FormState["ClientType"] = clientType;
    setIsValidCompany(!(clientType == "Company"));
    updateFormState(formState)
  }

  const getCompanyStatus = async (event: any) => {
    await axios.get("http://localhost:3000/", {params: {companyName: companyName}})
    .then((response) => {setCanProceed({canProceed: response.data});})
    .catch((err) => console.log(err));

    formState.FormState["CompanyNameCheck"] = companyName;
    updateFormState(formState);
  }

  useEffect(() => {
    if (formState.FormState["ClientType"] && formState.FormState["ClientType"] == "Company"){
      setIsValidCompany(false);
      setCanProceed({canProceed: false})
    } else {
      setCanProceed({canProceed: true})
    }
  }, [isValidCompany])

  return(
    <div>
      <p className="requiredField">Fields marked with * are required</p>
      <span>Client Name: </span>
      <input name="ClientName" defaultValue={formState["ClientName"]} onChange={(e) => {formState["ClientName"] = e.target.value; updateFormState(formState)}}></input>
      <div className="dropdown">
        <span className="formLabel">Client Type:*</span>
        <select name="ClientType" defaultValue={formState.FormState["ClientType"]} onChange={onClientTypeChanged}>
          <option> Individual </option>
          <option> Company </option>
        </select>
        { !isValidCompany && <div> <p>Is valid company check: what is company registry number of this company?</p>
        <input defaultValue={companyName} onChange={(e) => {setCompanyName(e.target.value);}} />
        <button type="button" onClick={getCompanyStatus}>Submit to Companies House</button>
        </div>
        }
      </div>

      <Dropdown name="Office" label="Office:" options={["Norwich"]} updateState={updateFormState} formState={formState} required={true} />

      <Dropdown name="Department" label="Department:" options={["Business"]} updateState={updateFormState} formState={formState} required={true}/>

      <Dropdown name="Partner" label="Partner:" options={["Generated by db request"]} updateState={updateFormState} formState={formState} required={true}/>

      <InputField name="Manager" label="Manager:" updateState={updateFormState} formState={formState}/> 

      <InputField name="CaseWorker" label="Case Worker:" updateState={updateFormState} formState={formState}/>
    </div>
  )
}

export default Page1
